version: "3.2"

services:
  portfolio_db:
    image: postgres:13.0-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres-data: