# Generated by Django 4.1.1 on 2022-09-13 13:24

import apps.portfolio.abstract.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=apps.portfolio.abstract.fields.CustomImageField(storage=apps.portfolio.abstract.fields.OverwriteStorage, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'name')},
        ),
    ]
