# Generated by Django 4.1.1 on 2022-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_photos_image_alter_photos_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
